"""ReasoningBank — stores and retrieves agent strategies and lessons learned.

Phase 1 (retrieval): embed query → cosine search → prepend top-k to SYSTEM_PROMPT
Phase 2 (construction): distill 1 memory item after each agent run via local LM
Phase 3 (consolidation): persist to local JSON cache + Notion "ReasoningBank" page
"""

import os
import re
import json
import math
import uuid
import logging
from datetime import datetime

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

logger = logging.getLogger(__name__)

_BANK_PAGE_TITLE = "ReasoningBank"
_LOCAL_CACHE_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "reasoning_bank.json")

# ─── Module-level state ───────────────────────────────────────────────────────

_items: list[dict] = []
_notion_page_id: str | None = None
_cache_loaded: bool = False

# ─── LM Studio helpers ────────────────────────────────────────────────────────

def _lm_client() -> OpenAI:
    return OpenAI(
        base_url=os.getenv("LMSTUDIO_BASE_URL", "http://host.docker.internal:1234/v1"),
        api_key=os.getenv("LMSTUDIO_API_KEY", "lm-studio"),
    )


def _embed(text: str) -> list[float] | None:
    """Embed text via LM Studio embeddings API. Returns None if unavailable."""
    try:
        emb_model = os.getenv("EMBEDDING_MODEL", "")
        client = _lm_client()
        kwargs: dict = {"input": text[:4096]}
        if emb_model:
            kwargs["model"] = emb_model
        resp = client.embeddings.create(**kwargs)
        return resp.data[0].embedding
    except Exception as exc:
        logger.debug("Embedding unavailable, falling back to keyword scoring: %s", exc)
        return None


def _cosine(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(x * x for x in b))
    if na == 0.0 or nb == 0.0:
        return 0.0
    return dot / (na * nb)


def _keyword_score(query: str, item: dict) -> float:
    """Word-overlap fallback — used when embeddings are unavailable."""
    q_words = set(query.lower().split())
    candidate = (item.get("query", "") + " " + item.get("summary", "")).lower()
    t_words = set(candidate.split())
    if not q_words:
        return 0.0
    return len(q_words & t_words) / len(q_words)


# ─── Notion helpers ───────────────────────────────────────────────────────────

def _notion_client():
    load_dotenv(override=False)
    from notion_client import Client  # lazy import — avoid circular dep
    return Client(auth=os.getenv("NOTION_API_KEY"))


def _normalize_id(raw: str) -> str:
    hex_only = re.sub(r"[^0-9a-fA-F]", "", raw)
    if len(hex_only) == 32:
        return (
            f"{hex_only[:8]}-{hex_only[8:12]}-{hex_only[12:16]}-"
            f"{hex_only[16:20]}-{hex_only[20:]}"
        )
    return raw.strip()


def _get_root_page_id() -> str:
    load_dotenv(override=False)
    return _normalize_id(os.getenv("NOTION_PARENT_PAGE_ID", ""))


def _find_or_create_bank_page() -> str:
    """Return Notion page ID for ReasoningBank, creating it under root if absent."""
    global _notion_page_id
    if _notion_page_id:
        return _notion_page_id

    nc = _notion_client()
    root_id = _get_root_page_id()

    # Search for an existing page with this exact title
    try:
        resp = nc.search(query=_BANK_PAGE_TITLE, page_size=20)
        for result in resp.get("results", []):
            if result.get("object") != "page":
                continue
            for prop in result.get("properties", {}).values():
                if prop.get("type") == "title":
                    title_text = "".join(
                        p.get("plain_text", "") for p in prop.get("title", [])
                    ).strip()
                    if title_text == _BANK_PAGE_TITLE:
                        _notion_page_id = result["id"]
                        logger.info("ReasoningBank page found: %s", _notion_page_id)
                        return _notion_page_id
    except Exception as exc:
        logger.warning("ReasoningBank Notion search error: %s", exc)

    # Not found — create it under the root page
    if not root_id:
        logger.error("NOTION_PARENT_PAGE_ID not set; cannot create ReasoningBank page.")
        return ""
    try:
        page = nc.pages.create(
            parent={"type": "page_id", "page_id": root_id},
            properties={"title": [{"type": "text", "text": {"content": _BANK_PAGE_TITLE}}]},
            children=[
                {
                    "object": "block",
                    "type": "callout",
                    "callout": {
                        "rich_text": [{"type": "text", "text": {
                            "content": "Auto-generated by the agent. Stores strategies and lessons learned."
                        }}],
                        "icon": {"type": "emoji", "emoji": "🧠"},
                    },
                }
            ],
        )
        _notion_page_id = page["id"]
        logger.info("ReasoningBank page created: %s", _notion_page_id)
        return _notion_page_id
    except Exception as exc:
        logger.error("Failed to create ReasoningBank page: %s", exc)
        return ""


def _append_item_to_notion(item: dict) -> None:
    """Append one memory item to the Notion page as readable text + JSON code block."""
    page_id = _find_or_create_bank_page()
    if not page_id:
        return

    outcome_emoji = "✅" if item.get("outcome") == "success" else "⚠️"
    md_text = (
        f"{outcome_emoji} [{item['timestamp']}] — {item['outcome'].upper()}\n"
        f"Query: {item['query']}\n"
        f"Strategy: {item['summary']}"
    )
    # Drop embedding vector before persisting to Notion (too large / not human-readable)
    storable = {k: v for k, v in item.items() if k != "embedding"}
    json_str = json.dumps(storable, indent=2)[:2000]

    blocks = [
        {"object": "block", "type": "divider", "divider": {}},
        {
            "object": "block",
            "type": "paragraph",
            "paragraph": {"rich_text": [{"type": "text", "text": {"content": md_text}}]},
        },
        {
            "object": "block",
            "type": "code",
            "code": {
                "rich_text": [{"type": "text", "text": {"content": json_str}}],
                "language": "json",
            },
        },
    ]
    try:
        _notion_client().blocks.children.append(block_id=page_id, children=blocks)
    except Exception as exc:
        logger.warning("Could not append item to Notion ReasoningBank: %s", exc)


# ─── Local cache ──────────────────────────────────────────────────────────────

def _load_local() -> list[dict]:
    try:
        with open(_LOCAL_CACHE_PATH) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return []


def _save_local(items: list[dict]) -> None:
    try:
        os.makedirs(os.path.dirname(_LOCAL_CACHE_PATH), exist_ok=True)
        with open(_LOCAL_CACHE_PATH, "w") as f:
            json.dump(items, f, indent=2)
    except Exception as exc:
        logger.warning("Could not write local reasoning bank cache: %s", exc)


# ─── LLM judge ───────────────────────────────────────────────────────────────

def _judge(user_message: str, agent_response: str, tool_errors: list[str]) -> str:
    """Ask the local LM to judge whether the task was completed successfully.

    Returns 'success' or 'failure'. Falls back to a length heuristic if the
    judge call itself fails.
    """
    if tool_errors:
        return "failure"
    prompt = (
        "Did this agent response fully and correctly complete the user's request?\n\n"
        f"User request: {user_message[:300]}\n"
        f"Agent response: {agent_response[:500]}\n\n"
        "Answer with only YES or NO."
    )
    try:
        resp = _lm_client().chat.completions.create(
            model=os.getenv("MODEL", "local-model"),
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            max_tokens=512,
        )
        answer = (resp.choices[0].message.content or "").strip().upper()
        return "success" if answer.startswith("YES") else "failure"
    except Exception:
        return "failure" if len(agent_response.strip()) < 30 else "success"


# ─── Public API ───────────────────────────────────────────────────────────────

def load() -> None:
    """Load items from the local JSON cache (fast path)."""
    global _items, _cache_loaded
    if _cache_loaded:
        return
    _items = _load_local()
    _cache_loaded = True
    logger.info("ReasoningBank loaded %d items from local cache.", len(_items))


def retrieve(query: str, top_k: int = 3) -> list[dict]:
    """Return up to top_k items most relevant to query (by embedding or keyword overlap)."""
    load()
    if not _items:
        return []

    query_emb = _embed(query)
    scored: list[tuple[float, dict]] = []
    for item in _items:
        if query_emb and item.get("embedding"):
            score = _cosine(query_emb, item["embedding"])
        else:
            score = _keyword_score(query, item)
        scored.append((score, item))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [item for score, item in scored[:top_k] if score > 0.0]


def distill(
    user_message: str,
    agent_response: str,
    tool_errors: list[str] | None = None,
) -> dict | None:
    """Ask the local LM to distill one reusable insight from this interaction.

    Returns a dict with: id, timestamp, query, outcome, summary, embedding.
    Returns None if distillation fails.
    """
    tool_errors = tool_errors or []
    outcome = _judge(user_message, agent_response, tool_errors)

    error_block = ""
    if tool_errors:
        error_block = "\n\nTool errors encountered:\n" + "\n".join(
            f"- {e}" for e in tool_errors[:5]
        )

    prompt = (
        "You are a meta-learning assistant. Analyze this agent interaction and write "
        "ONE concise strategy or lesson (max 2 sentences). No preamble, no JSON, no bullets.\n\n"
        f"User request: {user_message[:400]}\n"
        f"Agent response: {agent_response[:500]}"
        f"{error_block}\n\n"
        f"Outcome: {outcome}"
    )

    try:
        resp = _lm_client().chat.completions.create(
            model=os.getenv("MODEL", "local-model"),
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=512,
        )
        summary = (resp.choices[0].message.content or "").strip()
        if not summary:
            return None

        item = {
            "id": str(uuid.uuid4()),
            "timestamp": datetime.utcnow().isoformat(),
            "query": user_message[:300],
            "outcome": outcome,
            "summary": summary,
            "embedding": _embed(summary + " " + user_message[:200]),
        }
        return item
    except Exception as exc:
        logger.warning("ReasoningBank distill failed: %s", exc)
        return None


def save(item: dict) -> None:
    """Persist a new item to local cache and Notion (Phase 3 consolidation)."""
    global _items
    load()
    _items.append(item)
    _save_local(_items)
    _append_item_to_notion(item)
    logger.info(
        "ReasoningBank saved: %s (%s)", item.get("id", "?"), item.get("outcome", "?")
    )


def format_strategies_for_prompt(items: list[dict]) -> str:
    """Format retrieved strategies as a compact block for the system prompt."""
    if not items:
        return ""
    lines = ["## Relevant strategies from past experience:"]
    for i, item in enumerate(items, 1):
        label = "Success strategy" if item.get("outcome") == "success" else "Lesson learned"
        lines.append(f"{i}. [{label}] {item['summary']}")
    return "\n".join(lines)
